### ISSUE TITLE
v0.1.2 Release

### ISSUE THREAD

**Issue by pkmgarcia** [raghavgupta96/gratis-webapp#38]
## Projected Release Date
February 23rd, 2019

## Task List
- [x] Input validation for E-mail textfield (is a string, is an email)
- [x] Input validation for password textfield (is a string)
- [x] Dialog input validation for event title (is a string)
- [x] Dialog input validation for description (is a string)
- [x] Dialog input validation for start date & time (is a timestamp)
- [x] Dialog input validation for end date & time (is a timestamp)
- [x] Dialog input validation for tags (is a string)
- [x] Dialog input validation for allergies (is a string)
- [x] File input validation (is an image file)
- [x] Implement view profile function
- [x] Added tabs for mobile navigation
- [x] Added logos to header, sidebar
- [x] Updated Card UI (view/edit, and delete are encapsulated in vertical pop-up menu)
- [x] Added event codes (random, 4 digit number)
- [x] Fixed random styling issues (container heights, etc.)
- [x] Delete Events now requires confirmation
- [ ] Implement edit profile
- [ ] Edit profile area input validation (is a string)
- [ ] Edit profile cuisine input validation (is a string)
- [ ] Edit profile name input validation (is a string)
- [ ] Match edit profile UI with wireframe.
- [ ] Match view profile UI with wireframe.
- [ ] Fixed showstopper bug (#37)
- [ ] ~~Edit profile operational hours input validation (?)~~
